version: 2.1
jobs:
  update-metadata:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - release-management/configure-github
      - run: yarn
      - run: node ./generate-supported-metadata.js
      - run: git push
workflows:
  version: 2
  update-metadata:
    triggers:
      - schedule:
          cron: 0 0 * * 4
          filters:
            branches:
              only:
                - main
    jobs:
      - update-metadata:
          filters:
            branches:
              only: main
  test-ts-update:
    triggers:
      - schedule:
          cron: 0 0 * * *
          filters:
            branches:
              only:
                - main
    jobs:
      - release-management/test-ts-update
orbs:
  release-management: salesforce/npm-release-management@4
